metadata:
  type: OpenMLTD.MilliSim.Extension.Components.ScoreComponents.Configuration.ComboNumbersConfig
  assembly_file: OpenMLTD.MilliSim.Extension.Components.ScoreComponents.dll
  for: component.score.combo_numbers
  version: 1 # format version
data:
  images:
    file: res/images/numbers/combo.png # 0-9, 48x48 each
    count: 10
    orientation: horizontal
    blank_edge:
      left: 6
      right: 6
  layout:
    x: 89% # x position (anchor: right)
    y: 22% # y position (anchor: bottom)
