metadata:
  type: OpenMLTD.MilliSim.Extension.Components.ScoreComponents.Configuration.RibbonConfig
  assembly_file: OpenMLTD.MilliSim.Extension.Components.ScoreComponents.dll
  for: component.score.ribbon
  version: 1 # format version
data:
  image:
    file: res/images/ui/ribbon.png # 128x128
    blank_edge:
      left: 18
      top: 12
      right: 18
      bottom: 12
  opacity: 100%
